import os

DATABASE_HOST = os.getenv('SQL_HOST')
DATABASE_NAME = os.getenv('POSTGRES_DB')
DATABASE_USER = os.getenv('POSTGRES_USER')
DATABASE_PASSWORD = os.getenv('POSTGRES_PASSWORD')
DATABASE_PORT = os.getenv('SQL_PORT')


DOCS_DEFAULT_USERNAME = os.getenv('DOCS_DEFAULT_USERNAME')
DOCS_DEFAULT_PASSWORD = os.getenv('DOCS_DEFAULT_PASSWORD')
